import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Weather",
  description: "Generated by mazaharul islam",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
        {children}
        <Toaster
  position="top-center"
  reverseOrder={false}
/>
      </body>
    </html>
  );
}


